### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by xxami**
as a new user to nim and libcurl, i was a bit confused about what version of the library i should use with this, and it was also a bit difficult to use without a reference - had to make some creative use out of the github search and c examples.

so here is some links and a simple use case to help anyone that has the same problem. unless the author is against readmes for some reason, then oh well, i tried :P

### CODE REVIEW

**Comment by geekrelief** [comment]
@xxami Thanks for posting the README

I'm trying to make use of libcurl, but my executable keeps complaining it can't load libcurl.dll.  I tried the downloading the Windows dlls to the same directory as my exe, but no go.  It seems like the dll is being loaded from my nim/bin directory which is in my Path.  I tried the 32-bit dll on a whim, and I get an error about the wrong architecture, so the exe seems to be attempting to load it.  When I try the 64-bit dll I just get an "Error loading library" message.

I also tried loading libcurl-x64.dll using dynlib and also get the "Error loading library" message.

Any help would be appreciated.  Thanks!

**Comment by xxami** [comment]
@geekrelief i used the 64bit dll from here: https://curl.haxx.se/windows/
and renamed it to libcurl.dll, placed in the same directory as your executable :)

**Comment by geekrelief** [comment]
Strange, you would think it's as simple as that.  

I'm new to nim as well so it could be user error, but I tried making my own simple dll just to be sure I wasn't doing something wrong and I had no issue there.

Just thinking out loud, if it's not a path issue (renamed and put in the exe directory), not an import issue (I'm able to load my own dll), not a dll issue (you're able to load libcurl-x64.dll after renaming it), what could it be?

**Comment by geekrelief** [comment]
Alright I figured out what was going wrong. Basically had to create a C++ app to get the error code from LoadLibrary to figure out what was going wrong.  193: wrong architecture, gotta make sure libcurl.dll is 64-bit since the exe is 64-bit. 126: file not found, I created directory for nim dlls and put it at the front of the path.  127: proc not found, libcurl.dll has dependencies. One version depends on zlib and the on from the curl maintainers needs libssl and libcrypt.  I took the libcurl and zlib dlls I built with vcpkg and sure they were built with the 64-bit flag and put them together in my nim dlls folder.  Now everything works!  

I used Dependency Walker to look into the dlls for clues as to what was going wrong. 

While chatting with Yardanico I found out compiling with -d:nimDebugDlOpen should spit out error codes for dynlib or something but it's not documented anywhere, and supposedly error codes for loading libraries will be a thing in nim 1.4.

**Comment by xxami** [comment]
thanks for commenting the details, that sounds quite nasty :c

interesting that you mention the one from the curl maintainers requiring libssl, maybe because i was compiling using `-d:ssl` i didn't run into that issue

glad you got it sorted anyway :)

**Pull request merged**
